- name: DOCKER - Install apps
  aur:
    name:
      - podman # docker alternative
      - podman-docker # docker command support for podman
      - podman-dnsname # enable hostname resolution in docker-compose files

- name: DOCKER - Enable podman service
  systemd:
    name: podman
    state: started
    enabled: yes
  become: true

# TODO: change default subnet with podman
# - name: DOCKER - Change default subnet
#   copy:
#     src: daemon.json
#     dest: /etc/docker/daemon.json
#     owner: root
#     group: root
#     mode: 0644
#   notify: restart docker
#   become: true