- name: Create filesystem in root volume
  filesystem:
    dev: '{{ "/dev/mapper/cryptroot" if use_encryption else root_part }}'
    fstype: '{{ "btrfs" if use_btrfs else "ext4" }}'
    opts: '-L ArchLinux'
    force: yes

- name: Mount root filesystem
  mount:
    path: /mnt
    src: '{{ "/dev/mapper/cryptroot" if use_encryption else root_part }}'
    fstype: '{{ "btrfs" if use_btrfs else "ext4" }}'
    state: mounted
